geojson_stat(stat.name = "orientations",
             geojson.path = "C:/Rprojects/eamenaR/inst/extdata/caravanserail.geojson",
             ids = ref_ids("hp.id", ids.path = "C:/Rprojects/eamenaR/inst/extdata/ids.csv"),
             dirOut = "C:/Rprojects/eamenaR/results/",
             stat = "stats",
             chart.type = "radar",
             field.names = c("Resource Orientation"),
             fig.width = 9,
             fig.height = 8,
             write.stat = T)
